const Text = {
     navList: [
          { title: "Mầm xanh", id: "/mamxanh" },
          // { title: "Hoạt động", id: "/activity" },
          { title: "Ban chủ nhiệm", id: "/info" },
          { title: "Ban tổ chức", id: "/host" },
          { title: "Hình ảnh", id: "/Images/tetyeuthuong" },
          { title: "Liên hệ", id: "/contact" },
     ],
     event: [
          { title: "Tiêu biểu", id: "/Images/" },
          { title: "Tết Yêu Thương", id: "/Images/tetyeuthuong" },
          { title: "Tết Thiếu Nhi", id: "/Images/tetthieunhi" },
          { title: "Tết Trung Thu", id: "/Images/tettrungthu" },
          { title: "Áo Ấm Mùa Đông", id: "/Images/aoam" },
          { title: "Giáng Sinh Ấm Áp", id: "/Images/noel" },
          { title: "Tuyển Tình Nguyện Viên", id: "/Images/tuyentnv" },
          { title: "PROM NIGHT", id: "/Images/prom" },
     ],
     activity: [
          "Tết Yêu Thương",
          "Tết Thiếu Nhi",
          "Tết Trung Thu",
          "Giáng Sinh Ấm Áp",
          "Áo Ấm Mùa Đông",
          "Mái Ấm Tre Xanh",
          "Nhóm dạy Bình Triệu",
          "Nhóm dạy Ung Bướu",
          "Làng thiếu niên Thủ Đức",
     ],
     Year: [
          { year: "2021 - 2022", link: "/info" },
          { year: "2020 - 2021", link: "/info/f12" },
          { year: "2019 - 2020", link: "/info/f11" },
          { year: "2018 - 2019", link: "/info/f10" },
          { year: "2017 - 2018", link: "/info/f09" },
          { year: "2016 - 2017", link: "/info/f08" },
          { year: "2015 - 2016", link: "/info/f07" },
     ],
};
export default Text;
